apiVersion: v1
kind: Service
metadata:
  name: dashboard-front-service
  labels:
    app: dashboard-front
spec:
  type: LoadBalancer
  selector:
    app: dashboard-front
  ports:
    - port: 32188
      protocol: TCP
      targetPort: 3000
      nodePort: 32188